# Generated by Django 5.1.4 on 2024-12-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("birdid", "0002_waterbird_water_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="waterbird",
            name="description",
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
