# Generated by Django 5.1.4 on 2024-12-11 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("birdid", "0003_waterbird_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="waterbird",
            name="image_bird",
            field=models.ImageField(blank=True, default="fallback.png", upload_to=""),
        ),
    ]
