# Generated by Django 5.1.4 on 2024-12-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("birdid", "0004_waterbird_image_bird"),
    ]

    operations = [
        migrations.CreateModel(
            name="Raptor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "image_bird",
                    models.ImageField(blank=True, default="fallback.png", upload_to=""),
                ),
            ],
        ),
    ]
