# Generated by Django 5.1.4 on 2024-12-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("birdid", "0005_raptor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="raptor",
            name="image_bird",
            field=models.ImageField(
                blank=True, default="coopers_hawk.jpg", upload_to=""
            ),
        ),
    ]
